name: Linting
on:
  push:
    branches:
      - ux
      - ux/*
      - fix
      - fix/*
  pull_request:
      - main
      - ux
      - fix
jobs:
  'Checking':
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: '        Install'
        shell: bash
        run: |
          pnpm i
      - name: '        Lint'
        shell: bash
        run: |
          pnpm lint
      - name: '        Tests'
        shell: bash
        env:
          OS: ${{ matrix.os }}
        run: |
          pnpm test:unit
